# Generated by Django 5.2.5 on 2025-08-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_remove_attendance_status_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.employee'),
        ),
    ]
