# Generated by Django 5.2.4 on 2025-08-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0006_alter_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fms.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Worker', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
    ]
