# Generated by Django 5.2.4 on 2025-08-31 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_employee_bonus_percentage_employeeprofile_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='employee_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='fms.employeeprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='production',
            unique_together={('employee_profile', 'date')},
        ),
    ]
