# Generated by Django 5.2.4 on 2025-08-31 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_production_employee_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.employee'),
        ),
    ]
