# Generated by Django 5.0.6 on 2025-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0009_alter_employeeprofile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='raw_material_name',
            field=models.CharField(default='Cotton', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
